#!/usr/bin/env python3
"""Payload generator for the Butter crackme.

This is the ONLY place the accepted password exists in plaintext. crackme.exe
never contains it: it can only be recovered by decrypting the payload and
inverting the bytecode VM. Distribute the compiled exe, never this file.

What it produces: blob_data.h (the encrypted payload, compiled into the exe).

The cipher below must stay byte-for-byte in sync with decrypt_blob() in
crackme.c:

    key = derive_key()                     (see JUNK / LCG below)
    kb  = key as 4 little-endian bytes
    prev = 0x5A
    for i in 0..n-1:
        c       = rotl8(blob[i], 3)
        c       = c - (prev*3 + i)          (mod 256)
        plain[i] = c ^ kb[i % 4]
        prev    = plain[i]

Payload plaintext layout (little endian):

    0      : magic  b"CKR1"
    4      : u16 secret length
    6      : u16 bytecode length
    8      : secret bytes
    8+slen : bytecode for the VM

The VM program checks, for every character i:

    rotl8(input[i] ^ mask[i], rot[i]) == secret[i]

so the accepted password is PASSWORD, but recovering it requires decrypting the
payload *and* parsing the bytecode for mask[]/rot[].
"""
import os
import sys

PASSWORD = b"ClutterDecompilersGoBrrr_2026"  # must match the shipped crackme.exe; do not rebrand

# Must match g_junk[] in crackme.c. These look like ordinary hash constants.
JUNK = [
    0x9E3779B9, 0x85EBCA6B, 0xC2B2AE35, 0x27D4EB2F,
    0x165667B1, 0x2545F491, 0x94D049BB, 0xBF58476D,
    0x9FB21C65, 0x7FEB352D, 0x846CA68B, 0xDB4F0B91,
    0xA1E38F1D, 0x3E9841A3, 0x5BD1E995, 0x1B873593,
]

# VM opcodes (mirrored in crackme.c)
OP_NOP = 0x00
OP_PUSH_ARG = 0x11
OP_PUSH_IMM = 0x2A
OP_XOR = 0x37
OP_ROTL = 0x4C
OP_SECRET = 0x55
OP_CMPNE = 0x68
OP_LEN = 0x73
OP_ACCEPT = 0x8E
OP_HALT = 0xF0

INIT = 0x5A


def rotl8(v, n):
    n &= 7
    if n == 0:
        return v & 0xFF
    return ((v << n) | (v >> (8 - n))) & 0xFF


def rotr8(v, n):
    n &= 7
    if n == 0:
        return v & 0xFF
    return ((v >> n) | (v << (8 - n))) & 0xFF


def derive_key():
    k = 0x9E3779B9
    for j in JUNK:
        k = (k * 1103515245 + 12345) & 0xFFFFFFFF
        k ^= j
        k ^= k >> 7
    return k


def encrypt(plain, key):
    kb = [(key >> (8 * i)) & 0xFF for i in range(4)]
    out = bytearray(len(plain))
    prev = INIT
    for i, p in enumerate(plain):
        c = (p ^ kb[i % 4])
        c = (c + ((prev * 3) & 0xFF) + i) & 0xFF
        out[i] = rotr8(c, 3)
        prev = p
    return bytes(out)


def build_plaintext():
    # Deterministic mask/rotate schedule, derived from the key so it is not
    # sitting in the binary as a separate table.
    rng = (derive_key() ^ 0xC0FFEE) & 0xFFFFFFFF

    def nextb():
        nonlocal rng
        rng = (rng * 1664525 + 1013904223) & 0xFFFFFFFF
        return (rng >> 16) & 0xFF

    masks = [nextb() for _ in PASSWORD]
    rots = [1 + (nextb() % 7) for _ in PASSWORD]
    secret = bytes(rotl8(p ^ m, r) for p, m, r in zip(PASSWORD, masks, rots))

    code = bytearray([OP_LEN, len(PASSWORD)])
    for i in range(len(PASSWORD)):
        code += bytes(
            [
                OP_NOP,
                OP_PUSH_ARG, i,
                OP_PUSH_IMM, masks[i],
                OP_XOR,
                OP_PUSH_IMM, rots[i],
                OP_ROTL,
                OP_SECRET, i,
                OP_CMPNE,
            ]
        )
    code += bytes([OP_ACCEPT, OP_HALT])

    plain = b"CKR1" + len(secret).to_bytes(2, "little") + len(code).to_bytes(2, "little")
    plain += secret + bytes(code)
    return plain, masks, rots, secret, code


def main():
    plain, masks, rots, secret, code = build_plaintext()
    blob = encrypt(plain, derive_key())

    here = os.path.dirname(os.path.abspath(__file__))
    header = os.path.join(here, "blob_data.h")
    with open(header, "w") as f:
        f.write("/* Generated by gen_blob.py -- do not edit.\n")
        f.write(" * Encrypted payload for the Butter crackme. */\n")
        f.write("#define G_BLOB_LEN %du\n\n" % len(blob))
        f.write("static const unsigned char g_blob[G_BLOB_LEN] = {\n")
        for i in range(0, len(blob), 12):
            row = ", ".join("0x%02X" % b for b in blob[i:i + 12])
            f.write("    %s,\n" % row)
        f.write("};\n")

    print("wrote %s (%d bytes)" % (header, len(blob)))
    print("  plaintext payload: %d bytes (%d secret, %d bytecode)"
          % (len(plain), len(secret), len(code)))
    print("  accepted password : %r" % PASSWORD.decode())
    return 0


if __name__ == "__main__":
    sys.exit(main())
