set(BUTTER_DIR_NAME "rizin/butter")
if(WIN32)
    set(CMAKE_INSTALL_BINDIR "." CACHE PATH "Executable install directory")
    set(CMAKE_INSTALL_INCLUDEDIR "include" CACHE PATH "Include install directory")
    set(CMAKE_INSTALL_LIBDIR "lib" CACHE PATH "Library install directory")
    set(CMAKE_INSTALL_DATAROOTDIR "./" CACHE PATH "Resource installation directory")
    set(BUTTER_INSTALL_DATADIR "${CMAKE_INSTALL_DATAROOTDIR}" CACHE PATH "Resource installation directory")
elseif(APPLE)
    if (BUTTER_ENABLE_PACKAGING)
        set(CMAKE_INSTALL_INCLUDEDIR "include" CACHE PATH "Include install directory")
        set(CMAKE_INSTALL_LIBDIR "lib" CACHE PATH "Library install directory")
        set(CMAKE_INSTALL_DATAROOTDIR "./" CACHE PATH "Resource installation directory")
        set(CMAKE_INSTALL_BINDIR "../MacOS" CACHE PATH "Executable install directory") # BUNDLE step sets prefix to Resources
        set(BUTTER_INSTALL_DATADIR "${CMAKE_INSTALL_DATAROOTDIR}" CACHE PATH "Resource installation directory")
    else()
        include(GNUInstallDirs)
        set(BUTTER_INSTALL_DATADIR "${CMAKE_INSTALL_DATAROOTDIR}/${BUTTER_DIR_NAME}" CACHE PATH "Resource installation directory")
    endif()
else()
    include(GNUInstallDirs)
    set(BUTTER_INSTALL_DATADIR "${CMAKE_INSTALL_DATAROOTDIR}/${BUTTER_DIR_NAME}" CACHE PATH "Resource installation directory")
endif()
set(BUTTER_INSTALL_CONFIGDIR "${CMAKE_INSTALL_LIBDIR}/cmake/Butter" CACHE PATH "CMake file install location")
# Compatibility facade for out-of-tree plugins written against upstream Butter
# (see cmake/ButterCompat.cmake): a second package name pointing at this one.
set(BUTTER_COMPAT_CMAKE_CONFIGDIR "${CMAKE_INSTALL_LIBDIR}/cmake/Butter" CACHE PATH "CMake file install location for the Butter compatibility package")
