set(CLUTTER_DIR_NAME "rizin/clutter")
if(WIN32)
    set(CMAKE_INSTALL_BINDIR "." CACHE PATH "Executable install directory")
    set(CMAKE_INSTALL_INCLUDEDIR "include" CACHE PATH "Include install directory")
    set(CMAKE_INSTALL_LIBDIR "lib" CACHE PATH "Library install directory")
    set(CMAKE_INSTALL_DATAROOTDIR "./" CACHE PATH "Resource installation directory")
    set(CLUTTER_INSTALL_DATADIR "${CMAKE_INSTALL_DATAROOTDIR}" CACHE PATH "Resource installation directory")
elseif(APPLE)
    if (CLUTTER_ENABLE_PACKAGING)
        set(CMAKE_INSTALL_INCLUDEDIR "include" CACHE PATH "Include install directory")
        set(CMAKE_INSTALL_LIBDIR "lib" CACHE PATH "Library install directory")
        set(CMAKE_INSTALL_DATAROOTDIR "./" CACHE PATH "Resource installation directory")
        set(CMAKE_INSTALL_BINDIR "../MacOS" CACHE PATH "Executable install directory") # BUNDLE step sets prefix to Resources
        set(CLUTTER_INSTALL_DATADIR "${CMAKE_INSTALL_DATAROOTDIR}" CACHE PATH "Resource installation directory")
    else()
        include(GNUInstallDirs)
        set(CLUTTER_INSTALL_DATADIR "${CMAKE_INSTALL_DATAROOTDIR}/${CLUTTER_DIR_NAME}" CACHE PATH "Resource installation directory")
    endif()
else()
    include(GNUInstallDirs)
    set(CLUTTER_INSTALL_DATADIR "${CMAKE_INSTALL_DATAROOTDIR}/${CLUTTER_DIR_NAME}" CACHE PATH "Resource installation directory")
endif()
set(CLUTTER_INSTALL_CONFIGDIR "${CMAKE_INSTALL_LIBDIR}/cmake/Clutter" CACHE PATH "CMake file install location")
# Compatibility facade for out-of-tree plugins written against upstream Cutter
# (see cmake/CutterCompat.cmake): a second package name pointing at this one.
set(CLUTTER_COMPAT_CMAKE_CONFIGDIR "${CMAKE_INSTALL_LIBDIR}/cmake/Cutter" CACHE PATH "CMake file install location for the Cutter compatibility package")
